name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER@L}" >> "${GITHUB_ENV}"
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${OWNER_LC}/sensorsync-frontend:${{ github.sha }} .
          docker tag ghcr.io/${OWNER_LC}/sensorsync-frontend:${{ github.sha }} ghcr.io/${OWNER_LC}/sensorsync-frontend:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${OWNER_LC}/sensorsync-frontend:${{ github.sha }}
          docker push ghcr.io/${OWNER_LC}/sensorsync-frontend:latest